from enum import Enum

class DWSIMPackages(Enum):
    ActivityCoefficient = 'ActivityCoefficient'
    BlackOil = 'BlackOil'
    CAPEOPEN = 'CAPEOPEN'
    ChaoSeader = 'ChaoSeader'
    CoolProp = 'CoolProp'
    CoolPropIncompressibleMixture = 'CoolPropIncompressibleMixture'
    CoolPropIncompressiblePure = 'CoolPropIncompressiblePure'
    DebyeHuckel = 'DebyeHuckel'
    ElectrolyteBase = 'ElectrolyteBase'
    ElectrolyteNRTL = 'ElectrolyteNRTL'
    ExUNIQUAC = 'ExUNIQUAC'
    GraysonStreed = 'GraysonStreed'
    Raoult = 'Raoult'
    LKP = 'LKP'
    LIQUAC2 = 'LIQUAC2'
    MODFAC = 'MODFAC'
    NISTMFAC = 'NISTMFAC'
    NRTL = 'NRTL'
    PengRobinson = 'PengRobinson'
    PengRobinson1978 = 'PengRobinson1978'
    PengRobinsonLK = 'PengRobinsonLK'
    PRSV2 = 'PRSV2'
    PRSV2VL = 'PRSV2VL'
    Seawater = 'Seawater'
    SRK = 'SRK'
    SourWater = 'SourWater'
    SteamTables = 'SteamTables'
    UNIFAC = 'UNIFAC'
    UNIFACLL = 'UNIFACLL'
    UNIQUAC = 'UNIQUAC'
    Wilson = 'Wilson'